### ISSUE TITLE
Support newer version of Keycloak

### ISSUE THREAD

**Issue by Lexachoc** [prokie/fastapi-oidc-auth#15]
Hi @prokie,

Thank you for the fork and logout implementation!
I have a suggestion that `auth` should not be included in the well_known_pattern:
change well_known_pattern from 
`"{}/auth/realms/{}/.well-known/openid-configuration"`
to 
`"{}/realms/{}/.well-known/openid-configuration"`
to support a newer version of Keycloak with 'auth' removed in the URL.

**Comment by prokie** [comment]
Maybe one should integrate with https://pypi.org/project/python-keycloak/ instead, what do you think?

I think it would be great to support multiple versions of Keycloak. So should probably add that in the tests. At work we use version 16.I guess the latest version should be added to the tests as well. Do you think other versions are applicable aswell?

**Comment by rafalkrupinski** [comment]
Why is that path patter even in that class? It seems specific to a particular version of keycloak. Zitadel just uses `/.well-known/openid-configuration`

**Comment by prokie** [comment]
Solved
